package das.tickets.config;

public class RoleDefinition {

	public enum RoleName {
		ADMINISTRATOR, ASSIGNEE, VISITOR, REPORTER, MANAGER, ADMINISTRATOR1, ASSIGNEE1, VISITOR1, REPORTER1, MANAGER1, ADMINISTRATOR2, ASSIGNEE2, VISITOR2, REPORTER2, MANAGER2
	}

}
